### ISSUE TITLE
installation/deployment documentation

### ISSUE THREAD

**Issue by JosefAssad** [os2kitos/kitos#363]
It would be really nice if there was documentation for deployment of Kitos instances. I see the frontend deployment installation instructions, but it'd be nice to see something more comprehensive, including the C# backend.

Since we're wishing here, install instructions for Linux would also be great, especially if provided in the form of a Dockerfile. :)

**Comment by os2git** [comment]
Completely agree I don't personally have the full overview of what documentation is included in the latest version. But the common problem is that someone have to pay for the hours put into documentation. I guess you know what usually happen.

But it is on the list of tasks to be done when time and money permit it. Meanwhile you can contact Kitos office (info@kitos.dk ) or the primary supplier Miracle for help.

The most current version of Kitos is in the forked repro https://github.com/miracle-as/kitos it will be moved back to this OS2 repro once version 2.0 is fully implemented.
