### ISSUE TITLE
documentation for Kitos API

### ISSUE THREAD

**Issue by JosefAssad** [os2kitos/kitos#364]
Continuing my documentation wishlist, some docs specifically informing about the service interface would be absolutely great!

If #363 is fulfilled then together with this would be a great step forward for open interop.

And just to be greedy, a test instance? :)

**Comment by os2git** [comment]
Completely agree I don't personally have the full overview of what documentation is included in the latest version. But the common problem is that someone have to pay for the hours put into documentation. I guess you know what usually happen.

But it is on the list of tasks to be done when time and money permit it. Meanwhile you can contact Kitos office (info@kitos.dk ) or the primary supplier Miracle for help.

The most current version of Kitos is in the forked repro https://github.com/miracle-as/kitos it will be moved back to this OS2 repro once version 2.0 is fully implemented.

**Comment by JosefAssad** [comment]
Don't you want to keep these issues as a kind of public backlog? :) I can't be the only third party with who is keen on integrating to KITOS:

**Comment by os2git** [comment]
Kitos backlog is fully transparent on Jira. All OS2 projects are managed on Jira.
https://os2web.atlassian.net/projects/OS2KITOS/issues

Maintaining the backlog is not a central task in OS2 it is managed by the individual PM's and in this case the Kitos secretary is responsible for this. They are based in Ballerup Municipality and can be contacted on info@kitos.dk

I have forwarded notice about these two issues.

/Rasmus, OS2
